Narrativa API: COVID-19 data
Cathella/covid-stats-app pull request #1
Opened 2022-01-08 08:49 UTC by Cathella

In this pull request, I utilized the Narrativa API
[https://api.covid19tracking.narrativa.com/api/](https://api.covid19tracking.narrativa.com/api/)
[Link to the loom video](https://www.loom.com/share/56764664bfc74ec0b21c49c4f8d44287)
[Live demo link](https://compassionate-nightingale-86bf87.netlify.app/)

- [x] When the page loads, the app shows the list of categories that could be filtered out by some parameter, for example by the category name.
- [x] Displays some numeric values per category that come from the API.
- [x] When the user clicks (or taps) on a category item, the application navigates to the details page.
- [x] In the details page, the webapp retrieves data from the API to show detailed data in the category.
- [x] When the user clicks on the "Back" button (<), the user navigates to the home page.

### For the next reviewer, To see stats on the live demo, please select the previous date, because data for the current date is not currently available 🙏🏻.

2022-01-08 12:00 UTC, arslanbisharat requested changes
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- [ ] Please move these images to the correct directory. These are present in the main directory.
<img width="662" alt="Capture" src="https://user-images.githubusercontent.com/58504655/148643247-3f08a25f-d322-4f45-bd2f-49771db9647d.PNG">


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-01-08 12:00 UTC, arslanbisharat commented on src/components/Card.css
> +#searchInput {
- [ ] IDs shouldn't be used in selectors because these rules are too tightly coupled with the HTML and have no possibility of reuse. It's much preferred to use classes in selectors and then apply a class to an element on the page. Additionally, IDs impact your specificity and can lead to specificity wars.

2022-01-08 12:00 UTC, arslanbisharat commented on src/components/Card.css
> +#searchInput::placeholder {
- [ ] IDs shouldn't be used in selectors

2022-01-08 12:00 UTC, arslanbisharat commented on src/components/Region.js
> +/* eslint-disable react/prop-types */
- [ ] Let's not disable eslint rules.

2022-01-08 12:00 UTC, arslanbisharat commented on src/components/RegionCard.js
> +/* eslint-disable react/prop-types */
- [ ]  Let's not disable eslint rules.

2022-01-08 12:00 UTC, arslanbisharat commented on src/components/Search.js
> +/* eslint-disable react/prop-types */
- [ ]  Let's not disable eslint rules.

2022-01-08 12:00 UTC, arslanbisharat commented on README.md
> +Optionally, you can run the application [here]().
- [ ] Make sure you have deployed the application using Heroku, Netlify or GitHub Pages.

- [ ] The project is deployed properly, the home and detail page works as expected.


- [ ] A link to the deployed project is present in the README.

2022-01-08 12:00 UTC, arslanbisharat commented on README.md
> +> To read more information about running tests, visit [create react app website](https://create-react-app.dev/docs/running-tests/);
- [ ] There are not enough tests present in the project. There is one test and that is failing. 
<img width="331" alt="Capture" src="https://user-images.githubusercontent.com/58504655/148643383-7d2f2744-e0ff-495a-840d-a0c098355dfb.PNG">


- Make sure app has unit tests for several components of the app and some pure functions in Redux code.
- App has integration tests using React Testing Library
   * You can perform a mocking data fetching and Redux Store connection.

2022-01-09 01:46 UTC, enaburekhan approved these changes
Hi Cathella, 

Thank you for making all the changes requested by the last reviewer. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Code review by **Eric Enaburekhan**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-09 01:46 UTC, enaburekhan commented on src/components/Region.js
> +  const { data } = props;
**Optional**

- [ ] You can save one line of code by directly destructuring the `data` properties inside the function parameter like so:

```
const Region = ({ data }) => {
 other codes..
 .....
}
```

2022-01-09 01:53 UTC, merged